name: gecko_app
description: App de cuidado de geckos y reptiles
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  cached_network_image: ^3.3.1
  image_picker: ^1.2.1
  shared_preferences: ^2.0.15
  firebase_core: ^4.8.0
  cloud_firestore: ^6.4.0
  firebase_auth: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono_app.png"
  min_sdk_android: 21 # flutter_launcher_icons requires this to be set or it will use default
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
