// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4uSOewcTNHJhaDuRZPdEYPaqiwnWJdw',
    appId: '1:949074127931:web:68ef61e0bb8f07000dc01e',
    messagingSenderId: '949074127931',
    projectId: 'faunama-d9997',
    authDomain: 'faunama-d9997.firebaseapp.com',
    storageBucket: 'faunama-d9997.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9NgDOvrhlbaDaknmhwQ1pui4VKxcS3E',
    appId: '1:949074127931:android:7712237cd9c4de870dc01e',
    messagingSenderId: '949074127931',
    projectId: 'faunama-d9997',
    storageBucket: 'faunama-d9997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpGf26Sl5Blo6HD9f7OQEWPAyW74ajVYE',
    appId: '1:949074127931:ios:d43f4b445a5f545e0dc01e',
    messagingSenderId: '949074127931',
    projectId: 'faunama-d9997',
    storageBucket: 'faunama-d9997.firebasestorage.app',
    iosBundleId: 'com.example.geckoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpGf26Sl5Blo6HD9f7OQEWPAyW74ajVYE',
    appId: '1:949074127931:ios:d43f4b445a5f545e0dc01e',
    messagingSenderId: '949074127931',
    projectId: 'faunama-d9997',
    storageBucket: 'faunama-d9997.firebasestorage.app',
    iosBundleId: 'com.example.geckoApp',
  );
}
